### ISSUE TITLE
Android O support

### ISSUE THREAD

**Issue by schrnz** [Project-ARTist/ARTist#1]
Port ARTist to Android O in case it does not run out of the box.

**Comment by sweisgerber-dev** [comment]
see: Project-ARTist/art/issues/3

**Comment by sweisgerber-dev** [comment]
see: Project-ARTist/ArtistGui/issues/24

**Comment by sweisgerber-dev** [comment]
Notes to self:

- `art::HGraphBuilder`
- `art::HInstructionBuilder`

**Comment by sweisgerber-dev** [comment]
Implementation in art-branch: [artist_oreo_master](https://github.com/Project-ARTist/art/tree/artist_oreo_master) and artist-branch [feature_oreo_support](https://github.com/Project-ARTist/ARTist/tree/feature_oreo_support).

**Comment by sweisgerber-dev** [comment]
Moved to https://github.com/Project-ARTist/meta/issues/5
