### ISSUE TITLE
False positive for CodeLib-Signature

### ISSUE THREAD

**Issue by fYsh-de** [Project-ARTist/ARTist#8]
# Issue:
https://github.com/Project-ARTist/ARTist/blob/f066fb56c4f07259ab4108ad0aba848d197b0855/modules/module_manager.cc#L134

This comparison might be **true** for a non-exact matches.
Example:
searched_signature = Lsaarland/cispa/artist/codelib/Code**Lib;**
candidate_signature = **Lib;**
If ProGuard or any other obfuscation  is used the class **_ib_** isn't unlikely.

# Symptoms:
This falsely flags the base.apk as CodeLib and a following call of _ArtUtils::FindClassDefIdxFromName_
https://github.com/Project-ARTist/ARTist/blob/f066fb56c4f07259ab4108ad0aba848d197b0855/artist_utils.cc#L132
correctly, can't find a match to the CodeLib-Signature.
compare: https://github.com/Project-ARTist/ARTist/blob/f066fb56c4f07259ab4108ad0aba848d197b0855/artist_utils.cc#L137

# Possible Solutions:
Check if the returned index is exactly 0
or search for searched_signature inside of candidate_signature.

_ArtUtils::FindClassDefIdxFromName_ and _ModuleManager::definesClass_ do mostly the same and might better be merged.

**Comment by schrnz** [comment]
Thank you for reporting this, in this situation we should definitely check for a perfect match (hence 0 return value), then the ordering does not really matter since both need to be non-null anyway. 

I will also take care of refactoring the duplicate code.
